Updated typescript definitions
I was receiving the following typescript build error when converting from sweetalert to sweetalert2:

`error TS2349: Cannot invoke an expression whose type lacks a call signature. Type 'typeof 'sweetalert2'' has no compatible call signatures.`

I followed the [guidance here](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-function-d-ts.html) to convert the type definitions to a module-function declaration, which fixed my build issues.